// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	GetPersonByUsername(ctx context.Context, username string) (Person, error)
	GetRoomById(ctx context.Context, id int64) (Room, error)
	GetRoomsReservedDates(ctx context.Context, roomID int32) ([][]int32, error)
	UpdateCredit(ctx context.Context, arg UpdateCreditParams) error
}

var _ Querier = (*Queries)(nil)
