// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: room.sql

package database

import (
	"context"
)

const getRoomById = `-- name: GetRoomById :one
SELECT id, size, beds, floor, price
FROM room
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomById(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomById, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Beds,
		&i.Floor,
		&i.Price,
	)
	return i, err
}
